### ISSUE TITLE
Seekbar information icon view error.

### ISSUE THREAD

**Issue by apszika** [xbmc/skin.confluence#274] opened 2024-05-17 16:08 UTC
Hello!
(Sorry for my English.)

I circled the problem in red in the attached picture. Is there a solution to make the subtitle language icon appear properly?
There is no overscan, the picture appears fine otherwise.

System: CoreElec
Kodi: Omega (21) Official

![Képkivágás](https://github.com/xbmc/skin.confluence/assets/107860478/1713a4b9-f05c-4422-a92b-aff630aa524c)

Thank you in advance for your answer.

**Comment by Hitcher** [comment] 2024-05-17 19:52
Looks like the introduction of the HDR flag type has meant we need to decrease the title length.

Not sure why the HDR flag isn't visible for you though - can you post the MediaInfo of that video please?

**Comment by bossanova808** [comment] 2024-05-17 23:48
If you're working in this area @Hitcher - I recently happened to notice a little spacing issue too, between the resolution & HDR flag:

![image](https://github.com/xbmc/skin.confluence/assets/731309/84f28cb0-10e3-4965-b970-c4b667871432)

Just an eye worm but if you're in the area anyway....

**Comment by apszika** [comment] 2024-05-18 13:05
I only use SDR videos.
This is a different movie, but it's the same phenomenon with every video.
Do you mean this as media info?
![IMG_20240518_145749](https://github.com/xbmc/skin.confluence/assets/107860478/50320dc0-c4a8-4fc5-a3c5-05322ed00625)

**Comment by Hitcher** [comment] 2024-05-18 14:03
That empty space is where the HDR flag goes but if you're playing SDR videos there shouldn't even a gap there!

**Comment by apszika** [comment] 2024-05-18 14:15
I understand. Is there a way to correct this in the settings or anywhere?

**Comment by Hitcher** [comment] 2024-05-18 16:10
No, I'm just trying to figure out what's wrong.

**Comment by apszika** [comment] 2024-05-18 16:35
Thank you!

**Comment by Hitcher** [comment] 2024-05-18 20:30
Can you edit this file addons/skin.confluence/1080p/VideoFullscreen.xml using the code below to test please?

```
<?xml version="1.0" encoding="UTF-8"?>
<window>
	<defaultcontrol />
	<controls>
		<!-- view mode, sizing, screen resolution -->
		<control type="group" id="0">
			<depth>DepthOSD+</depth>
			<left>0</left>
			<top>30</top>
			<animation effect="fade" time="150">VisibleChange</animation>
			<control type="image">
				<description>media info background image</description>
				<left>0</left>
				<top>0</top>
				<width>1920</width>
				<height>240</height>
				<texture>black-back.png</texture>
			</control>
			<control type="label" id="10">
				<description>row 1 label</description>
				<left>75</left>
				<top>15</top>
				<width>1770</width>
				<height>45</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font12</font>
				<label />
			</control>
			<control type="label" id="11">
				<description>row 2 label</description>
				<left>75</left>
				<top>83</top>
				<width>1770</width>
				<height>45</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font12</font>
				<label />
			</control>
			<control type="label" id="12">
				<description>row 3 label</description>
				<left>75</left>
				<top>150</top>
				<width>1770</width>
				<height>68</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font12</font>
				<label />
			</control>
		</control>
		<!-- media infos -->
		<control type="group" id="1">
			<depth>DepthOSD</depth>
			<visible>[Player.ShowInfo | Window.IsActive(VideoOSD)] + ![Window.IsVisible(OSDSubtitleSettings) | Window.IsVisible(OSDVideoSettings) | Window.IsVisible(OSDAudioSettings) | Window.IsVisible(VideoBookmarks) | Window.IsVisible(PVROSDChannels) | Window.IsVisible(PVRChannelGuide) | Window.IsVisible(SliderDialog)]</visible>
			<animation effect="fade" time="150">VisibleChange</animation>
			<control type="image" id="1">
				<left>-30</left>
				<top>-225</top>
				<width>1980</width>
				<height>384</height>
				<texture flipy="true" border="1">HomeNowPlayingBack.png</texture>
			</control>
			<control type="label" id="1">
				<description>Chapter Count Header label</description>
				<left>45</left>
				<top>8</top>
				<width>1500</width>
				<height>38</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font13</font>
				<textcolor>white</textcolor>
				<shadowcolor>black</shadowcolor>
				<label>$INFO[Player.Chapter,$LOCALIZE[21396]: ]$INFO[Player.ChapterCount, / ]$INFO[Player.ChapterName,[COLOR=grey] - (,)[/COLOR]]</label>
				<visible>Player.ChapterCount + !VideoPlayer.Content(LiveTV)</visible>
			</control>
			<control type="label" id="1">
				<description>Channel Group label</description>
				<left>45</left>
				<top>8</top>
				<width>1500</width>
				<height>38</height>
				<align>left</align>
				<aligny>center</aligny>
				<font>font13</font>
				<textcolor>white</textcolor>
				<shadowcolor>black</shadowcolor>
				<label>$INFO[VideoPlayer.ChannelGroup,$LOCALIZE[31509]: ]</label>
				<visible>VideoPlayer.Content(LiveTV)</visible>
			</control>
			<control type="label" id="1">
				<description>Clock label</description>
				<left>675</left>
				<top>8</top>
				<width>1200</width>
				<height>38</height>
				<align>right</align>
				<aligny>center</aligny>
				<font>font13</font>
				<textcolor>white</textcolor>
				<shadowcolor>black</shadowcolor>
				<label>$INFO[System.Time]</label>
				<animation effect="slide" start="0,0" end="-45,0" time="0" condition="Player.Muted">conditional</animation>
				<animation effect="slide" start="0,0" end="-105,0" time="0" condition="system.getbool(input.enablemouse) + Window.IsVisible(VideoOSD)">conditional</animation>
			</control>
			<control type="image" id="1">
				<left>-30</left>
				<top>345r</top>
				<width>1980</width>
				<height>345</height>
				<texture border="1">HomeNowPlayingBack.png</texture>
			</control>
			<control type="image" id="1">
				<depth>DepthOSDPopout</depth>
				<description>cover image</description>
				<left>30</left>
				<top>390r</top>
				<width>450</width>
				<height>345</height>
				<texture fallback="DefaultVideoCover.png">$VAR[NowPlayingThumb]</texture>
				<aspectratio aligny="bottom">keep</aspectratio>
				<bordertexture infill="false" border="8">ThumbShadow.png</bordertexture>
				<bordersize>8</bordersize>
				<visible>![VideoPlayer.Content(Movies) | VideoPlayer.Content(LiveTV)]</visible>
			</control>
			<control type="image" id="1">
				<depth>DepthOSDPopout</depth>
				<description>Movie cover image</description>
				<left>30</left>
				<top>525r</top>
				<width>450</width>
				<height>495</height>
				<texture fallback="DefaultVideoCover.png">$VAR[NowPlayingThumb]</texture>
				<aspectratio aligny="bottom">keep</aspectratio>
				<bordertexture infill="false" border="8">ThumbShadow.png</bordertexture>
				<bordersize>8</bordersize>
				<visible>VideoPlayer.Content(Movies)</visible>
			</control>
			<control type="image" id="1">
				<depth>DepthOSDPopout</depth>
				<description>PIcon image</description>
				<left>30</left>
				<top>300r</top>
				<width>450</width>
				<height>225</height>
				<texture fallback="DefaultVideoCover.png">$INFO[Player.Art(thumb)]</texture>
				<aspectratio aligny="center">keep</aspectratio>
				<visible>VideoPlayer.Content(LiveTV)</visible>
			</control>
			<control type="group" id="1">
				<left>495</left>
				<top>278r</top>
				<control type="label" id="1">
					<description>Heading label</description>
					<left>0</left>
					<top>0</top>
					<width>1365</width>
					<height>38</height>
					<align>left</align>
					<aligny>center</aligny>
					<font>font13</font>
					<label>$LOCALIZE[31040]</label>
					<textcolor>white</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>![VideoPlayer.Content(LiveTV) + [PVR.IsRecordingPlayingChannel | PVR.IsPlayingActiveRecording]]</visible>
					<animation effect="slide" start="0,0" end="0,38" time="0" condition="!VideoPlayer.Content(Movies) + !VideoPlayer.Content(Episodes) + !VideoPlayer.Content(MusicVideos) + !VideoPlayer.Content(LiveTV) + !PVR.IsPlayingRecording">conditional</animation>
				</control>
				<control type="image" id="1">
					<top>0</top>
					<width>75</width>
					<height>38</height>
					<aspectratio align="center" aligny="center">keep</aspectratio>
					<texture>PVR-IsRecording.png</texture>
					<visible>VideoPlayer.Content(LiveTV) + [[PVR.IsRecordingPlayingChannel + !Player.ChannelPreviewActive] | PVR.IsPlayingActiveRecording]</visible>
				</control>
				<control type="label" id="1">
					<description>Heading label</description>
					<left>75</left>
					<top>0</top>
					<width>1290</width>
					<height>38</height>
					<align>left</align>
					<aligny>center</aligny>
					<font>font13</font>
					<label>$LOCALIZE[19158]</label>
					<textcolor>white</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>VideoPlayer.Content(LiveTV) + [[PVR.IsRecordingPlayingChannel + !Player.ChannelPreviewActive] | PVR.IsPlayingActiveRecording]</visible>
				</control>
				<control type="label" id="1">
					<description>Studio label</description>
					<left>30</left>
					<top>45</top>
					<width>1365</width>
					<height>38</height>
					<align>left</align>
					<font>font12</font>
					<label>$INFO[VideoPlayer.Studio]</label>
					<textcolor>grey2</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>VideoPlayer.Content(Movies)</visible>
				</control>
				<control type="label" id="1">
					<description>TV Show label</description>
					<left>30</left>
					<top>45</top>
					<width>1365</width>
					<height>38</height>
					<align>left</align>
					<font>font12</font>
					<label>$INFO[VideoPlayer.TVShowTitle] ($INFO[VideoPlayer.Season,,x]$INFO[VideoPlayer.Episode])</label>
					<textcolor>grey2</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>VideoPlayer.Content(Episodes)</visible>
				</control>
				<control type="label" id="1">
					<description>Music Info label</description>
					<left>30</left>
					<top>45</top>
					<width>1365</width>
					<height>38</height>
					<align>left</align>
					<font>font12</font>
					<label>$INFO[VideoPlayer.Artist] $INFO[VideoPlayer.Album, - ]</label>
					<textcolor>grey2</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>VideoPlayer.Content(MusicVideos)</visible>
				</control>
				<control type="label" id="1">
					<description>LiveTV Info label</description>
					<left>30</left>
					<top>45</top>
					<width>1365</width>
					<height>38</height>
					<align>left</align>
					<font>font12</font>
					<label>$INFO[VideoPlayer.ChannelNumberLabel,([COLOR=blue],[/COLOR]) ]$INFO[VideoPlayer.ChannelName]$INFO[VideoPlayer.EpisodeName, (,)]</label>
					<textcolor>grey2</textcolor>
					<shadowcolor>black</shadowcolor>
					<visible>VideoPlayer.Content(LiveTV) | PVR.IsPlayingRecording</visible>
				</control>
				<control type="grouplist" id="1">
					<left>30</left>
					<top>90</top>
					<width>1365</width>
					<height>53</height>
					<itemgap>8</itemgap>
					<orientation>horizontal</orientation>
					<control type="label" id="1">
						<width min="15" max="720">auto</width>
						<height>45</height>
						<font>font30</font>
						<align>left</align>
						<aligny>center</aligny>
						<label>$INFO[Player.Title]</label>
						<textcolor>orange</textcolor>
						<scroll>true</scroll>
					</control>
					<control type="image" id="1">
						<description>Video Resolution Image</description>
						<width>70</width>
						<height>53</height>
						<aspectratio align="center">keep</aspectratio>
						<texture>$INFO[VideoPlayer.VideoResolution,flagging/video/,.png]</texture>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.VideoResolution)</visible>
					</control>
					<control type="image" id="1">
						<description>Codec Image</description>
						<width>110</width>
						<height>53</height>
						<aspectratio align="left">keep</aspectratio>
						<texture>$INFO[VideoPlayer.HdrType,flagging/video/,.png]</texture>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.HdrType)</visible>
					</control>
					<control type="image" id="1">
						<description>Audio Codec Image</description>
						<width>110</width>
						<height>53</height>
						<aspectratio align="center">keep</aspectratio>
						<texture>$INFO[VideoPlayer.AudioCodec,flagging/audio/,.png]</texture>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.AudioCodec)</visible>
					</control>
					<control type="image" id="1">
						<description>Audio Channels Image</description>
						<width>70</width>
						<height>53</height>
						<aspectratio align="center">keep</aspectratio>
						<texture>$INFO[VideoPlayer.AudioChannels,flagging/audio/,.png]</texture>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.AudioChannels)</visible>
					</control>
					<control type="group" id="1">
						<width>110</width>
						<height>53</height>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.AudioLanguage)</visible>
						<control type="image" id="1">
							<top>0</top>
							<description>Audio Language Image</description>
							<width>110</width>
							<height>53</height>
							<texture>flagging/AudioLang.png</texture>
						</control>
						<control type="label" id="1">
							<left>49</left>
							<top>5</top>
							<width>71</width>
							<height>53</height>
							<font>font13</font>
							<align>left</align>
							<label>$INFO[VideoPlayer.AudioLanguage]</label>
							<textcolor>grey</textcolor>
						</control>
					</control>
					<control type="group" id="1">
						<width>110</width>
						<height>53</height>
						<visible>!Player.ChannelPreviewActive + !String.IsEmpty(VideoPlayer.SubtitlesLanguage)</visible>
						<control type="image" id="1">
							<top>0</top>
							<width>110</width>
							<height>53</height>
							<texture>flagging/SubLang.png</texture>
						</control>
						<control type="label" id="1">
							<left>49</left>
							<top>5</top>
							<width>71</width>
							<height>53</height>
							<font>font13</font>
							<align>left</align>
							<label>$INFO[VideoPlayer.SubtitlesLanguage]</label>
							<textcolor>grey</textcolor>
						</control>
					</control>
				</control>
				<control type="label" id="1">
					<left>0</left>
					<top>180</top>
					<width>1365</width>
					<height>38</height>
					<label>$LOCALIZE[31049] $INFO[Player.FinishTime]</label>
					<align>center</align>
					<aligny>center</aligny>
					<font>font12</font>
					<textcolor>grey</textcolor>
					<scroll>true</scroll>
					<visible>[Player.ShowInfo | Window.IsVisible(VideoOSD)] + !VideoPlayer.Content(LiveTV)</visible>
					<animation effect="fade" time="150">VisibleChange</animation>
				</control>
				<control type="label" id="1">
					<left>0</left>
					<top>180</top>
					<width>1365</width>
					<height>38</height>
					<label>$INFO[VideoPlayer.NextTitle,[B]$LOCALIZE[19031]: [/B]]</label>
					<align>center</align>
					<aligny>center</aligny>
					<font>font12</font>
					<textcolor>grey</textcolor>
					<scroll>true</scroll>
					<visible>!Window.IsVisible(VideoOSD) + VideoPlayer.Content(LiveTV)</visible>
					<animation effect="fade" time="150">VisibleChange</animation>
				</control>
				<control type="label" id="1">
					<left>0</left>
					<top>225</top>
					<width>1365</width>
					<height>38</height>
					<label>[B]$LOCALIZE[31961][/B] $INFO[PVR.TimeshiftCur] (-$INFO[PVR.TimeshiftOffset])</label>
					<align>center</align>
					<aligny>center</aligny>
					<font>font12</font>
					<textcolor>grey</textcolor>
					<scroll>true</scroll>
					<visible>!Window.IsVisible(VideoOSD) + VideoPlayer.Content(LiveTV) + PVR.IsTimeShift</visible>
					<animation effect="fade" time="150">VisibleChange</animation>
				</control>
			</control>
			<control type="group" id="1">
				<left>495</left>
				<top>143r</top>
				<visible>!VideoPlayer.Content(LiveTV) | [VideoPlayer.Content(LiveTV) + VideoPlayer.HasEpg]</visible>
				<control type="label" id="1">
					<visible>!VideoPlayer.Content(LiveTV)</visible>
					<left>0</left>
					<top>0</top>
					<width>150</width>
					<height>60</height>
					<font>font13</font>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[Player.Time(hh:mm:ss)]</label>
				</control>
				<control type="label" id="1">
					<visible>VideoPlayer.Content(LiveTV)</visible>
					<left>0</left>
					<top>0</top>
					<width>150</width>
					<height>60</height>
					<font>font13</font>
					<align>left</align>
					<aligny>center</aligny>
					<label>$INFO[VideoPlayer.StartTime]</label>
				</control>
				<control type="group" id="1">
					<visible>VideoPlayer.Content(LiveTV)</visible>
					<control type="progress" id="1">
						<description>ProgressbarTimeshift</description>
						<left>150</left>
						<top>23</top>
						<width>1080</width>
						<height>24</height>
						<info>PVR.TimeshiftProgressBufferEnd</info>
						<midtexture border="9,13,9,13">OSDProgressMidLight.png</midtexture>
						<visible>PVR.IsTimeShift</visible>
					</control>
					<control type="progress" id="1">
						<description>Progressbar</description>
						<left>150</left>
						<top>23</top>
						<width>1080</width>
						<height>24</height>
						<info>PVR.EpgEventProgress</info>
					</control>
				</control>
				<control type="group" id="1">
					<visible>!VideoPlayer.Content(LiveTV)</visible>
					<control type="progress" id="1">
						<description>ProgressbarCache</description>
						<left>150</left>
						<top>23</top>
						<width>1080</width>
						<height>24</height>
						<info>Player.ProgressCache</info>
						<midtexture border="9,13,9,13">OSDProgressMidLight.png</midtexture>
						<visible>!Player.ChannelPreviewActive</visible>
					</control>
					<control type="progress" id="1">
						<description>Progressbar</description>
						<left>150</left>
						<top>23</top>
						<width>1080</width>
						<height>24</height>
						<info>Player.Progress</info>
					</control>
				</control>
				<control type="label" id="1">
					<visible>!VideoPlayer.Content(LiveTV)</visible>
					<left>1230</left>
					<top>0</top>
					<width>150</width>
					<height>60</height>
					<font>font13</font>
					<align>right</align>
					<aligny>center</aligny>
					<label>$INFO[Player.Duration(hh:mm:ss)]</label>
				</control>
				<control type="label" id="1">
					<visible>VideoPlayer.Content(LiveTV)</visible>
					<left>1230</left>
					<top>0</top>
					<width>150</width>
					<height>60</height>
					<font>font13</font>
					<align>right</align>
					<aligny>center</aligny>
					<label>$INFO[VideoPlayer.EndTime]</label>
				</control>
				<control type="ranges" id="1">
					<description>Chapters</description>
					<left>150</left>
					<top>23</top>
					<width>1080</width>
					<height>24</height>
					<info>Player.Chapters</info>
					<texturebg border="9,13,9,13" colordiffuse="00FFFFFF">OSDProgressBack.png</texturebg>
					<righttexture border="3,8,3,5" colordiffuse="FFFFFFFF">OSDProgressNib.png</righttexture>
				</control>
				<control type="ranges" id="1">
					<description>Cuts</description>
					<left>150</left>
					<top>23</top>
					<width>1080</width>
					<height>24</height>
					<info>Player.Cuts</info>
					<texturebg border="9,13,9,13" colordiffuse="00FFFFFF">OSDProgressBack.png</texturebg>
					<righttexture border="3,8,3,5" colordiffuse="FFFF0000">OSDProgressNib.png</righttexture>
				</control>
				<control type="ranges" id="1">
					<description>Scene Markers</description>
					<left>150</left>
					<top>23</top>
					<width>1080</width>
					<height>24</height>
					<info>Player.SceneMarkers</info>
					<texturebg border="9,13,9,13" colordiffuse="00FFFFFF">OSDProgressBack.png</texturebg>
					<righttexture border="3,8,3,5" colordiffuse="FF0000FF">OSDProgressNib.png</righttexture>
				</control>
				<control type="ranges" id="1">
					<description>Editlist</description>
					<left>150</left>
					<top>23</top>
					<width>1080</width>
					<height>24</height>
					<info>Player.Editlist</info>
					<texturebg border="9,13,9,13" colordiffuse="00FFFFFF">OSDProgressBack.png</texturebg>
					<lefttexture border="3,8,3,5" colordiffuse="FFFFFFFF">OSDProgressNib.png</lefttexture>
					<midtexture colordiffuse="FFFF0000">colors/white.png</midtexture>
					<righttexture border="3,8,3,5" colordiffuse="FFFFFFFF">OSDProgressNib.png</righttexture>
				</control>
			</control>
		</control>
		<control type="label" id="1">
			<description>Seek Number label</description>
			<left>45</left>
			<top>8</top>
			<width>1830</width>
			<height>38</height>
			<align>center</align>
			<aligny>center</aligny>
			<font>font13</font>
			<textcolor>white</textcolor>
			<shadowcolor>black</shadowcolor>
			<label>$INFO[Player.SeekNumeric]</label>
		</control>
	</controls>
</window>
```

**Comment by apszika** [comment] 2024-05-19 09:03
You are awesome. Thank you very very much!
![1716108481630](https://github.com/xbmc/skin.confluence/assets/107860478/90686c85-215d-4c2d-8bec-a166207d5ff1)
I have one more question. Is it possible to make it so that when the FORCED subtitle is the active subtitle, the subtitle flag to be different from the FULL subtitle flag (e.g. different color)?

**Comment by Hitcher** [comment] 2024-05-19 09:33
> Is it possible to make it so that when the FORCED subtitle is the active subtitle, the subtitle flag to be different from the FULL subtitle flag (e.g. different color)?

There's no way for the skin to know if a subtitle is forced or not.

**Comment by Hitcher** [comment] 2024-05-19 09:36
I still don't understand why there's a blank space for the HDR type as that shouldn't happen if `VideoPlayer.HdrType` is empty.

Could you please change `<label>$INFO[Player.Title]</label>` to `<label>$INFO[VideoPlayer.HdrType]</label>` and tell me what is shown instead of the title please?

**Comment by apszika** [comment] 2024-05-19 10:12
> There's no way for the skin to know if a subtitle is forced or not.

Oh, I understand, Thank You!
 
> Could you please change to and tell me what is shown instead of the title please?`<label>$INFO[Player.Title]</label>``<label>$INFO[VideoPlayer.HdrType]</label>`

Happening this:
Instead of the file name, it just says SDR (circled in red) and the whole thing slips away.

![1716113160864](https://github.com/xbmc/skin.confluence/assets/107860478/55019667-99db-45e0-9129-8e0de32fb9dc)

**Comment by Hitcher** [comment] 2024-05-19 10:33
> Instead of the file name, it just says SDR (circled in red)

Thanks, that the info I needed. It means there's nothing wrong with the skin code but that there's something wrong with your setup.

Do you use NFO's or is everything just scraped normally?

**Comment by apszika** [comment] 2024-05-19 10:40
I thank you! :)
 I don't use scraper. I just open the movies as files.

**Comment by apszika** [comment] 2024-05-19 16:11
I found another little bug. Not a big bug, just a small ant. :) If subtitles are turned off, the subtitle flag will still be displayed. Like it's stuck. Is there anything else you can do with this? 
Thank you!

**Comment by Hitcher** [comment] 2024-05-19 16:51
It's not a bug as it's just showing you the media info for the video.

**Comment by Hitcher** [comment] 2024-05-19 16:59
@the-black-eagle any idea why `$INFO[VideoPlayer.HdrType]` is returning `sdr` as a label here?

**Comment by apszika** [comment] 2024-05-19 19:02
> It's not a bug as it's just showing you the media info for the video.

Previously, it only showed when subtitles were turned on. But I can live with it. :)

**Comment by Hitcher** [comment] 2024-05-19 20:52
So it was:

https://github.com/xbmc/skin.confluence/commit/a5fffc6ddb9451416a1e41078aa9a5470222e61c

Will add that back in for the next release.

**Comment by apszika** [comment] 2024-05-20 08:23
Okay, thank you very much for everything!!! :)

**Comment by Hitcher** [comment] 2024-05-20 09:38
Closing this now as completed.

As for your empty space where the HDR flag goes I can only assume it's CoreElec adding SDR to the VideoPlayer.HdrType label. Unless you have something creating NFO files.

**Comment by Hitcher** [comment] 2024-05-20 09:39
Closing this now as completed.

As for your empty space where the HDR flag goes I can only assume it's CoreElec adding SDR to the VideoPlayer.HdrType label. Unless you have something creating NFO files.

**Closed by Hitcher** 2024-05-20 09:39 UTC

**Comment by apszika** [comment] 2024-05-20 17:59
No problem, just for interesting. This is the same video in CoreElec - Kodi Leia 9.2.8 Official version. No hole:

![1716227053150](https://github.com/xbmc/skin.confluence/assets/107860478/47671bb1-0f5f-409a-9cc0-0c0b4712f1df)

**Comment by apszika** [comment] 2024-05-20 18:06
No problem, just for interesting. This is the same video in CoreElec - Kodi Leia 9.2.8 Official version. No hole:

![IMG_20240520_200331](https://github.com/xbmc/skin.confluence/assets/107860478/3cfd9ee4-5643-4fd0-8313-576ed8387557)

**Comment by Hitcher** [comment] 2024-05-20 19:22
Yeah the HDR label wasn't added back then.
